version: "3.9"
services:
  customer-db:
    image: "postgres"
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: customer
      POSTGRES_PASSWORD: customer
      POSTGRES_DB: customers
  customer-liquibase:
    depends_on:
      - customer-db
    image: "liquibase/liquibase"
    command: --url=jdbc:postgresql://customer-db:5432/customers --username=customer --password=customer --changeLogFile=changelog.xml update
    volumes:
      - ../liquibase/scripts/:/liquibase/scripts/
      - ../liquibase/changelog.xml:/liquibase/changelog.xml
